<?php

/**
 * @file
 * Contains astonshop.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function astonshop_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the astonshop module.
    case 'help.page.astonshop':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}
