<?php

/**
 * @file
 * Contains as_tshirt.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function as_tshirt_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the as_tshirt module.
    case 'help.page.as_tshirt':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('T-shirts feature for AstonShop website.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 * Register a module or theme's theme implementations.
 */
function as_tshirt_theme($existing, $type, $theme, $path) {

  return array(
    'tshirt_list' => array(
      'render element' => 'elements',
    ),
  );
}
